export const seedData = {
  profile: {
    id: "kano",
    display_name: "鹿乃まほろ",
    romanized_name: "Kano Mahoro",
    bio: "歌手 / Virtual Artist / みんなの毎日を、まほろばに。",
    avatar_url: "/assets/kano-avatar.jpg",
    banner_url: "/assets/kano-banner.jpg",
    x_url: "https://x.com/kano_2525",
    youtube_url: "https://www.youtube.com/channel/UCShXNLMXCfstmWKH_q86B8w",
    updated_at: "2026-08-27T23:00:00+09:00",
  },
  posts: [
    {
      id: "2092606390502400340",
      source: "x",
      type: "daily",
      label: "SONG / 感谢",
      text: "たくさん聴いてくれてありがとうございます。自分の人生を変えてくれた大切な曲で、またみんなに会えて、知ってもらえて嬉しいです。今までの私も、これからの私もよろしくね〜いっぱいまだまだ歌うよ！",
      published_at: "2026-08-26T22:33:36+09:00",
      url: "https://x.com/kano_2525/status/2092606390502400340",
      likes: 2334,
      reposts: 334,
      replies: 84,
      media_url: "https://pbs.twimg.com/media/HQpua-QbkAAeLek.jpg",
    },
    {
      id: "2092454708929872352",
      source: "x",
      type: "daily",
      label: "DAILY / 杂谈",
      text: "リズム天国、本気でやりすぎて筋肉痛になっちゃった…自分に自分でびっくりだよ🫠",
      published_at: "2026-08-26T12:30:53+09:00",
      url: "https://x.com/kano_2525/status/2092454708929872352",
      likes: 3553,
      reposts: 274,
      replies: 115,
      media_url: "https://pbs.twimg.com/media/HQniqvEaQAAPHv4.jpg",
    },
    {
      id: "2092160057542582386",
      source: "x",
      type: "notice",
      label: "ANNOUNCEMENT",
      text: "公式ソング担当のお知らせ。『ルル（タンフルタイム）』Official MV (feat. 鹿乃) が公開されました。歌もMVも、とってもとっても可愛いので是非チェックしてねえ。",
      published_at: "2026-08-25T17:00:02+09:00",
      url: "https://x.com/kano_2525/status/2092160057542582386",
      likes: 2310,
      reposts: 436,
      replies: 80,
      media_url: "https://pbs.twimg.com/media/HQjPgHSbQAAvOzt.jpg",
    },
    {
      id: "2092018224019968489",
      source: "x",
      type: "daily",
      label: "DAILY / 早安",
      text: "（みんな今日も「おはよ〜」って、まほろに言ってくれるかな？）",
      published_at: "2026-08-25T07:36:27+09:00",
      url: "https://x.com/kano_2525/status/2092018224019968489",
      likes: 5170,
      reposts: 374,
      replies: 737,
      media_url: "https://pbs.twimg.com/media/HQhWBglbsAAVXdd.jpg",
    },
    {
      id: "2091752948837863590",
      source: "x",
      type: "notice",
      label: "SCHEDULE / 本周",
      text: "今週のスケジュール。スケジュールだすの遅くなっちゃってごめんね。今週もいっぱいみんなと会えるの楽しみにしてるね。",
      published_at: "2026-08-24T14:02:20+09:00",
      url: "https://x.com/kano_2525/status/2091752948837863590",
      likes: 2480,
      reposts: 327,
      replies: 82,
      media_url: null,
      media_alt: "鹿乃まほろ的本周活动 schedule 图片",
    },
    {
      id: "2088969801817583799",
      source: "x",
      type: "notice",
      label: "ANNOUNCEMENT",
      text: "ミリプロSONA所属『鹿乃まほろ』です。8/22、みんなの心に癒しの魔法を！会えるのを楽しみにしています。",
      published_at: "2026-08-16T21:43:06+09:00",
      url: "https://x.com/kano_2525/status/2088969801817583799",
      likes: 17398,
      reposts: 4433,
      replies: 559,
      media_url: null,
    },
  ],
  events: [
    {
      id: "x-schedule-20260825",
      source: "x",
      source_item_id: "2091752948837863590",
      source_key: "2026-08-25T20:00",
      provenance: "manual",
      cancellation_status: "none",
      manual_locked: 1,
      title: "リズム天国 ミラクルスターズ",
      detail: "YouTube / 游戏配信",
      starts_at: "2026-08-25T20:00:00+09:00",
      status: "已完成",
      event_type: "stream",
      url: "https://www.youtube.com/watch?v=XbWL4SICA_k",
      is_upcoming: 0,
    },
    {
      id: "x-schedule-20260826",
      source: "x",
      source_item_id: "2091752948837863590",
      source_key: "2026-08-26T20:00",
      provenance: "manual",
      cancellation_status: "none",
      manual_locked: 1,
      title: "リズム天国 ミラクルスターズ",
      detail: "YouTube / 游戏配信",
      starts_at: "2026-08-26T20:00:00+09:00",
      status: "已完成",
      event_type: "stream",
      url: "https://www.youtube.com/watch?v=ACYi4lMKuG4",
      is_upcoming: 0,
    },
    {
      id: "x-schedule-20260827",
      source: "x",
      source_item_id: "2091752948837863590",
      source_key: "2026-08-27T20:00",
      provenance: "manual",
      cancellation_status: "none",
      manual_locked: 1,
      title: "配信内容は未定",
      detail: "YouTube / 20:00",
      starts_at: "2026-08-27T20:00:00+09:00",
      status: "待确认",
      event_type: "stream",
      url: "https://x.com/kano_2525/status/2091752948837863590",
      is_upcoming: 0,
    },
    {
      id: "x-schedule-20260828",
      source: "x",
      source_item_id: "2091752948837863590",
      source_key: "2026-08-28T22:00",
      provenance: "manual",
      cancellation_status: "none",
      manual_locked: 1,
      title: "メンバーシップ限定",
      detail: "鹿友以上〜 / 22:00",
      starts_at: "2026-08-28T22:00:00+09:00",
      status: "会员限定",
      event_type: "member",
      url: "https://www.youtube.com/channel/UCShXNLMXCfstmWKH_q86B8w/streams",
      is_upcoming: 1,
    },
    {
      id: "x-schedule-20260829",
      source: "x",
      source_item_id: "2091752948837863590",
      source_key: "2026-08-29T09:00",
      provenance: "manual",
      cancellation_status: "none",
      manual_locked: 1,
      title: "ミリプロファンミ",
      detail: "朝、なにかするかも？",
      starts_at: "2026-08-29T09:00:00+09:00",
      status: "待确认",
      event_type: "event",
      url: "https://x.com/kano_2525/status/2091752948837863590",
      is_upcoming: 1,
    },
    {
      id: "youtube-aH1DIRyDnfc",
      source: "youtube",
      source_item_id: "aH1DIRyDnfc",
      source_key: "reservation",
      provenance: "automatic",
      cancellation_status: "none",
      title: "50万人記念歌配信",
      detail: "歌枠 / YouTube Live",
      starts_at: "2026-08-30T21:00:00+09:00",
      status: "已预约",
      event_type: "stream",
      url: "https://www.youtube.com/watch?v=aH1DIRyDnfc",
      is_upcoming: 1,
    },
    {
      id: "youtube-C0goUsjfeTE",
      source: "youtube",
      source_item_id: "C0goUsjfeTE",
      source_key: "reservation",
      provenance: "automatic",
      cancellation_status: "none",
      title: "8月もおつかれさまでした。色々、ありましたね",
      detail: "メンバーシップ限定 / YouTube",
      starts_at: "2026-08-28T22:00:00+09:00",
      status: "会员限定",
      event_type: "member",
      url: "https://www.youtube.com/watch?v=C0goUsjfeTE",
      is_upcoming: 1,
    },
    {
      id: "youtube-0PISw7uR4UU",
      source: "youtube",
      source_item_id: "0PISw7uR4UU",
      source_key: "reservation",
      provenance: "automatic",
      cancellation_status: "none",
      title: "鹿乃まほろ加入記念グッズ",
      detail: "YouTube Live / 预约",
      starts_at: "2026-09-23T00:00:00+09:00",
      status: "已预约",
      event_type: "stream",
      url: "https://www.youtube.com/watch?v=0PISw7uR4UU",
      is_upcoming: 1,
    },
  ],
  videos: [
    {
      id: "ACYi4lMKuG4",
      source: "youtube",
      title:
        "【リズム天国 ミラクルスターズ】歌い手だし余裕…おや？難易度の様子が…？ #2",
      published_at: "2026-08-27T00:13:22+09:00",
      url: "https://www.youtube.com/watch?v=ACYi4lMKuG4",
      thumbnail_url: "https://i.ytimg.com/vi/ACYi4lMKuG4/hqdefault.jpg",
      kind: "GAMEPLAY",
      is_upcoming: 0,
    },
    {
      id: "XbWL4SICA_k",
      source: "youtube",
      title:
        "【リズム天国 ミラクルスターズ】歌い手なんだし余裕だよね！…だよね？ #1",
      published_at: "2026-08-26T00:07:00+09:00",
      url: "https://www.youtube.com/watch?v=XbWL4SICA_k",
      thumbnail_url: "https://i.ytimg.com/vi/XbWL4SICA_k/hqdefault.jpg",
      kind: "GAMEPLAY",
      is_upcoming: 0,
    },
    {
      id: "ZuklosiIA0A",
      source: "youtube",
      title:
        "【雑談】初配信ありがとうございましたヽ(.⊿·)【鹿乃まほろ/ミリプロ】",
      published_at: "2026-08-23T23:09:17+09:00",
      url: "https://www.youtube.com/watch?v=ZuklosiIA0A",
      thumbnail_url: "https://i.ytimg.com/vi/ZuklosiIA0A/hqdefault.jpg",
      kind: "TALK",
      is_upcoming: 0,
    },
    {
      id: "YzfwW0zTSpE",
      source: "youtube",
      title: "【#鹿乃まほろ初配信】みんなの毎日を、まほろばに！",
      published_at: "2026-08-22T21:37:42+09:00",
      url: "https://www.youtube.com/watch?v=YzfwW0zTSpE",
      thumbnail_url: "https://i.ytimg.com/vi/YzfwW0zTSpE/hqdefault.jpg",
      kind: "LIVE ARCHIVE",
      is_upcoming: 0,
    },
    {
      id: "aH1DIRyDnfc",
      source: "youtube",
      title: "【歌枠】みんなありがとう〜50万人記念歌配信！",
      published_at: null,
      scheduled_at: "2026-08-30T21:00:00+09:00",
      url: "https://www.youtube.com/watch?v=aH1DIRyDnfc",
      thumbnail_url: "https://i.ytimg.com/vi/aH1DIRyDnfc/hqdefault.jpg",
      kind: "UPCOMING LIVE",
      is_upcoming: 1,
    },
  ],
  focus: {
    id: 1,
    video_id: "YzfwW0zTSpE",
    date_label: "08.22 · 初配信",
    title: "みんなの毎日を、まほろばに。",
    description:
      "从歌い手到 Virtual Artist，鹿乃まほろ的新名字已经和新的舞台连在一起。这里收下每次歌、每次配信，以及下一次见面的线索。",
    image_url: null,
    url: "https://www.youtube.com/watch?v=YzfwW0zTSpE",
    source_url: "https://milpr.com/news/mahoro_debut",
    updated_at: "2026-08-23T00:00:00+09:00",
  },
  timeline: [
    {
      id: 1,
      year: "2026",
      title: "鹿乃まほろ",
      detail: "加入ミリプロSONA，开始 VTuber 活动。",
      sort_order: 1,
    },
    {
      id: 2,
      year: "2022",
      title: "MKLNtic",
      detail: "与ろん组成音乐组合。",
      sort_order: 2,
    },
    {
      id: 3,
      year: "2015",
      title: "Major debut",
      detail: "以《Stella-rium》正式出道。",
      sort_order: 3,
    },
    {
      id: 4,
      year: "2010",
      title: "第一首投稿",
      detail: "从 NicoNico 的歌唱投稿开始。",
      sort_order: 4,
    },
  ],
  resources: [
    {
      id: 1,
      title: "X / main",
      detail: "@kano_2525 · 近况首发",
      icon: "𝕏",
      tone: "coral",
      url: "https://x.com/kano_2525",
      sort_order: 1,
    },
    {
      id: 2,
      title: "X / sub",
      detail: "@_Kanotic · 个人向",
      icon: "𝕏",
      tone: "blue",
      url: "https://x.com/_Kanotic",
      sort_order: 2,
    },
    {
      id: 3,
      title: "YouTube / main",
      detail: "鹿乃まほろ · 配信与歌",
      icon: "▶",
      tone: "mint",
      url: "https://www.youtube.com/channel/UCShXNLMXCfstmWKH_q86B8w",
      sort_order: 3,
    },
    {
      id: 4,
      title: "YouTube / sub",
      detail: "鹿乃 / MKLNtic · 旧频道",
      icon: "▶",
      tone: "yellow",
      url: "https://www.youtube.com/channel/UCfuz6xYbYFGsWWBi3SpJI1w",
      sort_order: 4,
    },
    {
      id: 5,
      title: "bilibili",
      detail: "鹿乃ちゃん · 中文圈",
      icon: "哔",
      tone: "periwinkle",
      url: "https://space.bilibili.com/316381099",
      sort_order: 5,
    },
    {
      id: 6,
      title: "TwitCasting",
      detail: "直播存档与通知",
      icon: "◉",
      tone: "butter",
      url: "https://www.twitcasting.tv/kano_2525",
      sort_order: 6,
    },
    {
      id: 7,
      title: "ミリプロ / SONA",
      detail: "所属与官方公告",
      icon: "✦",
      tone: "coral",
      url: "https://milpr.com/news/mahoro_debut",
      sort_order: 7,
    },
    {
      id: 8,
      title: "NicoNico / mylist",
      detail: "早期投稿存档",
      icon: "▤",
      tone: "ink",
      url: "https://www.nicovideo.jp/user/15078610/mylist/16997570",
      sort_order: 8,
    },
    {
      id: 9,
      title: "旧 official site",
      detail: "更新截至 2022 · 资料存档",
      icon: "⌂",
      tone: "ink",
      url: "https://kano-official.amebaownd.com",
      sort_order: 9,
    },
  ],
  assets: [
    {
      id: "weekly-schedule",
      kind: "schedule",
      url: "",
      source_url: "https://x.com/kano_2525/status/2091752948837863590",
      alt: "鹿乃まほろ的本周活动 schedule 图片",
      week_start: "2026-08-24",
      source_account: "kano_2525",
    },
  ],
}
