export const seedData = {
  profile: {
    id: "kano",
    display_name: "鹿乃まほろ",
    romanized_name: "Kano Mahoro",
    bio: "歌手 / Virtual Artist / みんなの毎日を、まほろばに。",
    avatar_url: "/assets/kano-avatar.jpg",
    banner_url: "/assets/kano-banner.jpg",
    x_url: "https://x.com/kano_2525",
    youtube_url: "https://www.youtube.com/channel/UCShXNLMXCfstmWKH_q86B8w",
    updated_at: null,
  },
  posts: [],
  events: [],
  videos: [],
  focus: null,
  timeline: [
    {
      id: 1,
      year: "2026",
      title: "鹿乃まほろ",
      detail: "8 月加入ミリプロSONA，以新形象开始配信。",
      sort_order: 1,
    },
    {
      id: 2,
      year: "2022",
      title: "MKLNtic",
      detail: "与ろん组成音乐组合。",
      sort_order: 2,
    },
    {
      id: 5,
      year: "2021",
      title: "鹿乃まほろ",
      detail: "以粉发双马尾的まほろ形象开始配信。",
      sort_order: 3,
    },
    {
      id: 6,
      year: "2019",
      title: "花寄女子寮",
      detail: "以花寄女子寮成员身份开始 VTuber 活动。",
      sort_order: 4,
    },
    {
      id: 3,
      year: "2015",
      title: "Major debut",
      detail: "以《Stella-rium》正式出道。",
      sort_order: 5,
    },
    {
      id: 4,
      year: "2010",
      title: "第一首投稿",
      detail: "从 NicoNico 的歌唱投稿开始。",
      sort_order: 6,
    },
  ],
  resources: [
    {
      id: 1,
      title: "X / main",
      detail: "@kano_2525 · 近况首发",
      icon: "𝕏",
      tone: "coral",
      url: "https://x.com/kano_2525",
      sort_order: 1,
    },
    {
      id: 2,
      title: "X / sub",
      detail: "@_Kanotic · 个人向",
      icon: "𝕏",
      tone: "blue",
      url: "https://x.com/_Kanotic",
      sort_order: 2,
    },
    {
      id: 3,
      title: "YouTube / main",
      detail: "鹿乃まほろ · 配信与歌",
      icon: "▶",
      tone: "mint",
      url: "https://www.youtube.com/channel/UCShXNLMXCfstmWKH_q86B8w",
      sort_order: 3,
    },
    {
      id: 4,
      title: "YouTube / sub",
      detail: "鹿乃 / MKLNtic · 旧频道",
      icon: "▶",
      tone: "yellow",
      url: "https://www.youtube.com/channel/UCfuz6xYbYFGsWWBi3SpJI1w",
      sort_order: 4,
    },
    {
      id: 5,
      title: "bilibili",
      detail: "鹿乃ちゃん · 中文圈",
      icon: "哔",
      tone: "periwinkle",
      url: "https://space.bilibili.com/316381099",
      sort_order: 5,
    },
    {
      id: 6,
      title: "TwitCasting",
      detail: "直播存档与通知",
      icon: "◉",
      tone: "butter",
      url: "https://www.twitcasting.tv/kano_2525",
      sort_order: 6,
    },
    {
      id: 7,
      title: "ミリプロ / SONA",
      detail: "事务所个人页 · 资料与公告",
      icon: "✦",
      tone: "coral",
      url: "https://milpr.com/talents/kano-mahoro",
      sort_order: 7,
    },
    {
      id: 8,
      title: "NicoNico / mylist",
      detail: "早期投稿存档",
      icon: "▤",
      tone: "ink",
      url: "https://www.nicovideo.jp/user/15078610/mylist/16997570",
      sort_order: 8,
    },
    {
      id: 9,
      title: "official site",
      detail: null,
      icon: "⌂",
      tone: "ink",
      url: "https://kano-official.amebaownd.com",
      sort_order: 9,
    },
    {
      id: 10,
      title: "ミリプロ shop",
      detail: "事务所官方商店",
      icon: "✦",
      tone: "butter",
      url: "https://shop.milpr.com/",
      sort_order: 10,
    },
  ],
  assets: [],
}
